docs(scriptlets): improve inline documentation in scriptlets

diff --git a/scriptlets/_put b/scriptlets/_put
--- a/scriptlets/_put
+++ b/scriptlets/_put
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-# Transfer a file to a remote device via SCP.
+# Transfer files to a remote device via SCP.
 #
 # Description:
 #
@@ -8,34 +8,35 @@
 # which must be set. The user name on the remote device is `ubuntu`
 # by default, unless provided by the environment variable DEVICE_USER.
 #
-# This script depends on the `set_ssh_options` script to set SSH options.
+# The last argument provided is considered to be the "target", i.e. where
+# on the remote device the file(s) will be copied. If the last argument is
+# `--`, then the file(s) will be copied on the home directory of DEVICE_USER
+# (defaults to `ubuntu`)
+#
+# This script sources `defs/set_ssh_options` to set SSH_OPTS.
+# This script soures `defs/check_for_device_ip` to check that DEVICE_IP is set.
 #
 # Return value:
 #
 # 0 if the copy operation is successful or >0 in case of an error.
 
 usage() {
-    echo "Usage: $(basename ${BASH_SOURCE[0]}) <source> ... <target>"
+    echo "Usage: $(basename ${BASH_SOURCE[0]}) <source> ... -- | <target>"
 }
 
-parse_args() {
-    if [ $# -lt 2 ]; then
-        usage
-        echo "Error: <source> and/or <target> not specified"
-        exit 1
-    fi
+if [ $# -lt 2 ]; then
+    usage
+    echo "Error: <source> and/or <target> not specified"
+    exit 1
+fi
 
-    # The target is the last argument
-    export TARGET=${@: -1}
-    [[ "$TARGET" != "--" ]] || unset TARGET
+# The target is the last argument (unless the last argument is `--`)
+TARGET=${@: -1}
+[[ "$TARGET" != "--" ]] || unset TARGET
 
-    # Remove the target from the list by slicing the arguments array
-    SOURCES_ARRAY=("${@:1:$#-1}")
-    export SOURCES="${SOURCES_ARRAY[@]}"
-}
-
-
-parse_args $@
+# Remove the target from the list by slicing the arguments array
+SOURCES_ARRAY=("${@:1:$#-1}")
+SOURCES="${SOURCES_ARRAY[@]}"
 
 source "$(dirname ${BASH_SOURCE[0]})/defs/check_for_device_ip"
 source "$(dirname ${BASH_SOURCE[0]})/defs/ssh_options"
diff --git a/scriptlets/_run b/scriptlets/_run
--- a/scriptlets/_run
+++ b/scriptlets/_run
@@ -8,7 +8,8 @@
 # which must be set. The user name on the remote device is `ubuntu`
 # by default, unless provided by the environment variable DEVICE_USER.
 #
-# This script depends on the `set_ssh_options` script to set SSH options.
+# This script sources `defs/set_ssh_options` to set SSH_OPTS.
+# This script soures `defs/check_for_device_ip` to check that DEVICE_IP is set.
 #
 # Return value:
 #
@@ -19,16 +20,12 @@ usage() {
     echo "Usage: $(basename ${BASH_SOURCE[0]}) <command>"
 }
 
-parse_args() {
-    if [ $# -lt 1 ]; then
-        usage
-        echo "Error: <command> not specified"
-        exit 1
-    fi
-}
 
-
-parse_args $@
+if [ $# -lt 1 ]; then
+    usage
+    echo "Error: <command> not specified"
+    exit 1
+fi
 
 source "$(dirname ${BASH_SOURCE[0]})/defs/check_for_device_ip"
 source "$(dirname ${BASH_SOURCE[0]})/defs/ssh_options"
diff --git a/scriptlets/check_for_ssh b/scriptlets/check_for_ssh
--- a/scriptlets/check_for_ssh
+++ b/scriptlets/check_for_ssh
@@ -1,12 +1,16 @@
 #!/usr/bin/env bash
 
-# Check if a remote device is fully up and running
+# Check if a remote device is fully up and running.
 #
 # Description:
 #
-# The script runs `systemctl is-system-running` on the remote device,
-# so it succeeds: "when the system is fully up and running, meaning
+# The script runs `systemctl is-system-running` on the remote device.
+# It succeeds "when the system is fully up and running, meaning
 # not in startup, shutdown or maintainance mode."
+#
+# There are cases when `degraded` (rather than `running`), which signifies
+# a failure to start certain services, is also acceptable as a state, in
+# which case the `--allow-degraded` command-line flag should be provided.
 #
 # Return value:
 # 
@@ -18,24 +22,19 @@ usage() {
     echo "Usage: $(basename ${BASH_SOURCE[0]}) [--allow-degraded]"
 }
 
-parse_args() {
-    while [[ "$#" -gt 0 ]]; do
-        case $1 in
-            --allow-degraded)
-                export ALLOW_DEGRADED="(degraded allowed)"
-                ;;
-            *)
-                usage
-                echo "Error: Invalid argument $1"
-                exit 1
-                ;;
-        esac
-        shift
-    done
-}
-
-
-parse_args $@
+while [[ "$#" -gt 0 ]]; do
+    case $1 in
+        --allow-degraded)
+            ALLOW_DEGRADED="(degraded allowed)"
+            ;;
+        *)
+            usage
+            echo "Error: Invalid argument $1"
+            exit 1
+            ;;
+    esac
+    shift
+done
 
 echo "Checking if ${DEVICE_IP:-device} is fully up and running $ALLOW_DEGRADED"
 RESULT=$(_run systemctl is-system-running)
diff --git a/scriptlets/install_checkbox_agent_source b/scriptlets/install_checkbox_agent_source
--- a/scriptlets/install_checkbox_agent_source
+++ b/scriptlets/install_checkbox_agent_source
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-# Install Checkbox from repo, matching a specific version
+# Install Checkbox from repo, matching a specific version.
 #
 # Description:
 #
@@ -8,22 +8,35 @@
 # tool in order to checkout and install a version of Checkbox that matches
 # a specific version provided as an argument.
 #
-# The second argument, the `tools_path` is only necessary in order to locate
-# the `checkout_to_version` tool. It can be removed if that tool is installed
-# (it is currently not).
+# The second argument, the `tools_path` is necessary in order to locate the
+# `checkout_to_version` tool. It can be removed if that tool is installed (it
+# is currently not). The argument is also not required if TOOLS_PATH is set.
 
 usage() {
-    echo "Usage: $(basename $0) <version> <tools_path>"
+    echo "Usage: $(basename $0) <version> [<tools_path>]"
 }
 
-if [ $# -ne 2 ]; then
+if [ $# -gt 2 ]; then
     usage
-    echo "Error: incorrect number of arguments"
+    echo "Error: Too many arguments"
+    exit 1
+fi
+
+if [ $# -lt 1 ]; then
+    usage
+    echo "Error: <version> not specified"
     exit 1
 fi
 
 VERSION=$1
-TOOLS_PATH=$2
+
+if [ $# -eq 2 ]; then
+    TOOLS_PATH=$2
+elif [ -z "$TOOLS_PATH" ]; then
+    usage
+    echo "Error: <tools_path> not specified and TOOLS_PATH not set"
+    exit 1
+fi
 
 # clone Checkbox repo
 git clone --filter=tree:0 https://github.com/canonical/checkbox.git > /dev/null
diff --git a/scriptlets/wait_for_packages_complete b/scriptlets/wait_for_packages_complete
--- a/scriptlets/wait_for_packages_complete
+++ b/scriptlets/wait_for_packages_complete
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 #
-# Wait until package operations (apt, dpkg) are complete
+# Wait until package operations (apt, dpkg) are complete.
 #
 # See `check_for_packages_complete` (which is repeatedly called here)
 # for details.
@@ -21,17 +21,13 @@ usage() {
     echo "Usage: $(basename ${BASH_SOURCE[0]})"
 }
 
-parse_args() {
-    if [ $# -gt 0 ]; then
-        usage
-        echo "Error: invalid arguments $@"
-        exit 1
-    fi
-}
+if [ $# -gt 0 ]; then
+    usage
+    echo "Error: invalid arguments $@"
+    exit 1
+fi
 
-parse_args $@
-
-timeout 10m retry --delay 5 -- check_for_packages_complete
+timeout 10m retry --delay 10 -- check_for_packages_complete
 
 result=$?
 if [ $result -ge 124 ]; then
diff --git a/scriptlets/wait_for_ssh b/scriptlets/wait_for_ssh
--- a/scriptlets/wait_for_ssh
+++ b/scriptlets/wait_for_ssh
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-# Wait until a remote device is fully up and running
+# Wait until a remote device is fully up and running.
 # 
 # See `check_for_ssh` (which is repeatedly called here) for details
 #
@@ -16,27 +16,32 @@ usage() {
     echo "Usage: $(basename ${BASH_SOURCE[0]}) [--allow-degraded]"
 }
 
-parse_args() {
-    while [[ "$#" -gt 0 ]]; do
-        case $1 in
-            --allow-degraded)
-                export ALLOW_DEGRADED=$1
-                ;;
-            *)
-                usage
-                echo "Error: Invalid argument $1"
-                exit 1
-                ;;
-        esac
-        shift
-    done
-}
-
-
-parse_args $@
+TIMES=20
+DELAY=10
+while [[ "$#" -gt 0 ]]; do
+    case $1 in
+        --allow-degraded)
+            ALLOW_DEGRADED=$1
+            ;;
+        --times)
+            TIMES=$2
+            shift
+            ;;
+        --delay)
+            DELAY=$2
+            shift
+        *)
+            usage
+            echo "Error: Invalid argument $1"
+            exit 1
+            ;;
+    esac
+    shift
+done
 
 CHECK=check_for_ssh
-retry --times 20 --delay 10 --message $CHECK -- \
+# use `retry` to call `check_for_ssh` repeatedly
+retry --times $TIMES --delay $DELAY --message $CHECK -- \
 $CHECK $ALLOW_DEGRADED
 
 result=$?
