feat(scriptlets): re-implement elementary scriptlets

diff --git a/scriptlets/_put b/scriptlets/_put
--- a/scriptlets/_put
+++ b/scriptlets/_put
@@ -2,21 +2,32 @@
 
 # Transfer a file to a remote device via SCP.
 #
-# Dependencies:
-#   This script depends on the `set_ssh_options` script to set SSH options.
-#   DEVICE_IP and DEVICE_USER must be set in the environment.
+# Description:
 #
-# Usage:
-#   `_put <local_file> <remote_file>`
-#   Or source it in another script and call
-#   `put_function <local_file> <remote_file>`
+# The IP of the device is provided by the environment variable DEVICE_IP,
+# which must be set. The user name on the remote device is `ubuntu`
+# by default, unless provided by the environment variable DEVICE_USER.
+#
+# This script depends on the `set_ssh_options` script to set SSH options.
+#
+# Return value:
+#
+# 0 if the copy operation is successful or >0 in case of an error.
 
-put_function() {
-    source "$(dirname "$BASH_SOURCE")/set_ssh_options"
-    scp $SSH_OPTS $1 ${DEVICE_USER:-ubuntu}@$DEVICE_IP:$2
+usage() {
+    echo "Usage: $(basename $0) <local_file> <remote_file>"
 }
 
-# Check if the script is being sourced or executed
-if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
-    put_function "$@"
+if [ -z $DEVICE_IP ]; then
+    echo "Error: Environment variable DEVICE_IP not set"
+    exit 1
 fi
+
+if [ $# -lt 2 ]; then
+    usage
+    echo "Error: <local_file> and/or <remote_file> not specified"
+    exit 1
+fi
+
+source "$(dirname "$BASH_SOURCE")/set_ssh_options"
+scp $SSH_OPTS $1 ${DEVICE_USER:-ubuntu}@$DEVICE_IP:$2
diff --git a/scriptlets/_run b/scriptlets/_run
--- a/scriptlets/_run
+++ b/scriptlets/_run
@@ -2,21 +2,33 @@
 
 # Run a command on a remote device via SSH.
 #
-# Dependencies:
-#   This script depends on the `set_ssh_options` script to set SSH options.
-#   DEVICE_IP and DEVICE_USER must be set in the environment.
+# Description:
 #
-# Usage:
-#   `_run <command> [command_args ...]`
-#   Or source it in another script and call
-#   `run_function <command> [command_args ...]`
+# The IP of the device is provided by the environment variable DEVICE_IP,
+# which must be set. The user name on the remote device is `ubuntu`
+# by default, unless provided by the environment variable DEVICE_USER.
+#
+# This script depends on the `set_ssh_options` script to set SSH options.
+#
+# Return value:
+#
+# The value returned by the command on the remote device, or 255 in case
+# of an ssh error
 
-run_function() {
-    source "$(dirname "$BASH_SOURCE")/set_ssh_options"
-    ssh $SSH_OPTS ${DEVICE_USER:-ubuntu}@$DEVICE_IP "$@"
+usage() {
+    echo "Usage: $(basename $0) <command>"
 }
 
-# Check if the script is being sourced or executed
-if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
-    run_function "$@"
+if [ -z $DEVICE_IP ]; then
+    echo "Error: Environment variable DEVICE_IP not set"
+    exit 1
 fi
+
+if [ $# -lt 1 ]; then
+    usage
+    echo "Error: <command> not specified"
+    exit 1
+fi
+
+source "$(dirname "$BASH_SOURCE")/set_ssh_options"
+ssh $SSH_OPTS ${DEVICE_USER:-ubuntu}@$DEVICE_IP "$@"
