refactor(scriptlets): homogenise `_run` and `_put`

diff --git a/scriptlets/_run b/scriptlets/_run
--- a/scriptlets/_run
+++ b/scriptlets/_run
@@ -16,19 +16,20 @@
 # of an ssh error
 
 usage() {
-    echo "Usage: $(basename $0) <command>"
+    echo "Usage: $(basename ${BASH_SOURCE[0]}) <command>"
 }
 
-if [ -z $DEVICE_IP ]; then
-    echo "Error: Environment variable DEVICE_IP not set"
-    exit 1
-fi
+parse_args() {
+    if [ $# -lt 1 ]; then
+        usage
+        echo "Error: <command> not specified"
+        exit 1
+    fi
+}
 
-if [ $# -lt 1 ]; then
-    usage
-    echo "Error: <command> not specified"
-    exit 1
-fi
 
-source "$(dirname "$BASH_SOURCE")/defs/ssh_options"
+parse_args $@
+
+source "$(dirname ${BASH_SOURCE[0]})/defs/check_for_device_ip"
+source "$(dirname ${BASH_SOURCE[0]})/defs/ssh_options"
 ssh $SSH_OPTS ${DEVICE_USER:-ubuntu}@$DEVICE_IP "$@"
