feat(scriptlets): add `--allow-degraded` option to `check_for_ssh`

diff --git a/scriptlets/check_for_ssh b/scriptlets/check_for_ssh
--- a/scriptlets/check_for_ssh
+++ b/scriptlets/check_for_ssh
@@ -14,5 +14,29 @@
 # https://www.man7.org/linux/man-pages/man1/systemctl.1.html
 # or 255 in case of an ssh failure
 
+usage() {
+    echo "Usage: $(basename $0) [--allow-degraded]"
+}
+
+while [[ "$#" -gt 0 ]]; do
+    case $1 in
+        --allow-degraded)
+            ALLOW_DEGRADED="(degraded allowed)"
+            ;;
+        *)
+            usage
+            echo "Error: Invalid argument $1"
+            exit 1
+            ;;
+    esac
+    shift
+done
+
 echo "Checking if ${DEVICE_IP:-device} is fully up and running"
-_run systemctl is-system-running
+RESULT=$(_run systemctl is-system-running)
+echo $RESULT $ALLOW_DEGRADED
+if [ -z "$ALLOW_DEGRADED" ]; then
+    [[ "$RESULT" = "active" ]]
+else
+    [[ "$RESULT" =~ ^(active|degraded)$ ]]
+fi
