feat(scriptlets): Improve waiting for package-handling

diff --git a/scriptlets/check_for_packages_complete b/scriptlets/check_for_packages_complete
--- a/scriptlets/check_for_packages_complete
+++ b/scriptlets/check_for_packages_complete
@@ -4,30 +4,53 @@
 #
 # Description:
 #
-# The script uses `pgrep` to check if `apt` or `pkg` processes are running
-# as well as `fuser` to check if certain lock files are in use.
+# The script uses `pgrep` to check if `apt` or `dpkg` processes are running
+# as well as `fuser` to check if certain lock files are in use. If it
+# determines that package-handling operations are ongoing, it displays
+# information about the processes and files that are implicated.
+#
+# `fuser` may not be available on some systems. In these cases, please
+# use the `--no-files-check` command-line flag.
 #
 # Return value:
 #
 # 0 if no package operations are ongoing or 1 otherwise
 
-is_process_running() {
-    # The arg is the process name
-    pgrep "$1" > /dev/null 2>&1
+usage() {
+    echo "Usage: $(basename ${BASH_SOURCE[0]}) [--no-files-check]"
 }
 
-is_file_used() {
-    # The arg is the file name
-    fuser -s "$1"
-}
+NO_FILES_CHECK=""
+while [[ "$#" -gt 0 ]]; do
+    case $1 in
+        --no-files-check)
+            NO_FILES_CHECK=", no checking of lock files"
+            ;;
+        *)
+            usage
+            echo "Error: Invalid argument $1"
+            exit 1
+            ;;
+    esac
+    shift
+done
 
-is_resource_busy() {
-    is_process_running apt || \
-    is_process_running dpkg || \
-    is_file_used /var/lib/apt/lists/lock || \
-    is_file_used /var/lib/dpkg/lock || \
-    is_file_used /var/cache/debconf/config.dat
-}
-
-echo "Checking if package handling (apt, dpkg) is ongoing"
-is_resource_busy && exit 1 || exit 0
+echo "Checking if package handling is ongoing (apt, dpkg$NO_FILES_CHECK)"
+PROCESSES=$(pgrep --list-full "^apt|dpkg")
+PROCESSES_RESULT=$?
+if [ -z "$NO_FILES_CHECK" ]; then
+    FILES=$(sudo fuser /var/lib/apt/lists/lock /var/lib/dpkg/lock /var/lib/dpkg/lock-frontend /var/cache/debconf/config.dat 2>&1)
+    FILES_RESULT=$?
+else
+    FILES=""
+    FILES_RESULT=1
+fi
+if [ $PROCESSES_RESULT -eq 0 ] || [ $FILES_RESULT -eq 0 ]; then
+    echo Package handling is ongoing
+    echo -e "Processes:\n$PROCESSES"
+    [ -n "$FILES" ] && echo -e "Files:\n$FILES"
+    exit 1
+else
+    echo No ongoing package handling
+    exit 0
+fi
diff --git a/scriptlets/wait_for_packages_complete b/scriptlets/wait_for_packages_complete
--- a/scriptlets/wait_for_packages_complete
+++ b/scriptlets/wait_for_packages_complete
@@ -11,27 +11,48 @@
 #
 # Return value:
 # 
-# 0 if `check_for_packages_complete` is successful
+# 0 if `check_for_packages_complete` is successful, or a timeout has occurred
 # 1 if `check_for_packages_complete` cannot be executed or is unsuccesful on the last retry
-# >=124 in case of a timeout
-# https://manpages.ubuntu.com/manpages/focal/man1/retry.1.html
-# https://man7.org/linux/man-pages/man1/timeout.1.html
 
 usage() {
-    echo "Usage: $(basename ${BASH_SOURCE[0]})"
+    echo "Usage: $(basename ${BASH_SOURCE[0]}) [--no-files-check]"
 }
 
-if [ $# -gt 0 ]; then
-    usage
-    echo "Error: invalid arguments $@"
-    exit 1
-fi
+NO_FILES_CHECK=""
+TIMEOUT="10m"
+DELAY=10
+while [[ "$#" -gt 0 ]]; do
+    case $1 in
+        --no-files-check)
+            NO_FILES_CHECK=$1
+            ;;
+        --timeout)
+            TIMEOUT=$2
+            shift
+            ;;
+        --delay)
+            DELAY=$2
+            shift
+            ;;
+        *)
+            usage
+            echo "Error: Invalid argument $1"
+            exit 1
+            ;;
+    esac
+    shift
+done
 
-timeout 10m retry --delay 10 -- check_for_packages_complete
+timeout "$TIMEOUT" retry --delay "$DELAY" -- check_for_packages_complete $NO_FILES_CHECK
 
 result=$?
 if [ $result -ge 124 ]; then
-    echo "Unable to complete $(basename ${BASH_SOURCE[0]}) (timeout). Killing apt, apt-get, and dpkg processes."
-    sudo pkill -x "apt|apt-get|dpkg"
+    # the `retry` has timed out
+    echo "$(basename ${BASH_SOURCE[0]}) has timed out".
+    echo "Killing apt, apt-get, and dpkg processes:"
+    sudo pkill --echo -x "apt|apt-get|dpkg"
+    # indicate success:
+    # since the processes have been killed, package handling is no longer ongoing
+    exit 0
 fi
 exit $result
