feat(scriptlets): refine `wait_for_ssh`

diff --git a/scriptlets/check_for_ssh b/scriptlets/check_for_ssh
--- a/scriptlets/check_for_ssh
+++ b/scriptlets/check_for_ssh
@@ -18,25 +18,31 @@ usage() {
     echo "Usage: $(basename $0) [--allow-degraded]"
 }
 
-while [[ "$#" -gt 0 ]]; do
-    case $1 in
-        --allow-degraded)
-            ALLOW_DEGRADED="(degraded allowed)"
-            ;;
-        *)
-            usage
-            echo "Error: Invalid argument $1"
-            exit 1
-            ;;
-    esac
-    shift
-done
+parse_args() {
+    while [[ "$#" -gt 0 ]]; do
+        case $1 in
+            --allow-degraded)
+                export ALLOW_DEGRADED="(degraded allowed)"
+                ;;
+            *)
+                usage
+                echo "Error: Invalid argument $1"
+                exit 1
+                ;;
+        esac
+        shift
+    done
+}
 
-echo "Checking if ${DEVICE_IP:-device} is fully up and running"
+
+parse_args $@
+echo "Checking if ${DEVICE_IP:-device} is fully up and running $ALLOW_DEGRADED"
 RESULT=$(_run systemctl is-system-running)
-echo $RESULT $ALLOW_DEGRADED
+STATUS=$?
+[ -n "$RESULT" ] && echo $RESULT
+# check returned result and propagate `_run`'s exit status if not successful
 if [ -z "$ALLOW_DEGRADED" ]; then
-    [[ "$RESULT" = "running" ]]
+    [[ "$RESULT" = "running" ]] || exit $STATUS
 else
-    [[ "$RESULT" =~ ^(running|degraded)$ ]]
+    [[ "$RESULT" =~ ^(running|degraded)$ ]] || exit $STATUS
 fi
diff --git a/scriptlets/wait_for_ssh b/scriptlets/wait_for_ssh
--- a/scriptlets/wait_for_ssh
+++ b/scriptlets/wait_for_ssh
@@ -12,8 +12,29 @@
 # https://manpages.ubuntu.com/manpages/focal/man1/retry.1.html
 # https://man7.org/linux/man-pages/man1/timeout.1.html
 
+usage() {
+    echo "Usage: $(basename $0) [--allow-degraded]"
+}
+
+parse_args() {
+    while [[ "$#" -gt 0 ]]; do
+        case $1 in
+            --allow-degraded)
+                export ALLOW_DEGRADED=$1
+                ;;
+            *)
+                usage
+                echo "Error: Invalid argument $1"
+                exit 1
+                ;;
+        esac
+        shift
+    done
+}
+
+parse_args $@
 retry --times 20 --delay 10 --message "check_for_ssh" -- \
-timeout 10s check_for_ssh
+timeout 10s check_for_ssh $ALLOW_DEGRADED
 
 result=$?
 if [ $result -gt 0 ]; then
