[CERTTF-425] Scriptlets for minimal SRU job (#58)
* feat: add `dist-upgrade` option to `install_packages`
* feat: add scriptlets for the minimal SRU workflow
- `collect_artifacts`
- `enable_proposed`
- `install_package_from_proposed`
* feat: introduce `log` function
* feat: refactor `fetch_manifest` and extend it to handle default
* feat: extend `scenario` to handle list values
* feat: extend `install_checkbox_debs` to handle providers
* feat: retrieve `DEVICE_USER` from the scenario in the installer
* feat: include `submission.log` in the collected artifacts
* feat: refine pinning and installing from proposed
* chore: use exceptions to communicate fetching results

diff --git a/scriptlets/install_checkbox_debs b/scriptlets/install_checkbox_debs
--- a/scriptlets/install_checkbox_debs
+++ b/scriptlets/install_checkbox_debs
@@ -19,28 +19,52 @@
 # Returns:
 # 0 on success, non-0 on failure
 
-if [[ "$#" != "1" ]]; then
-  echo "Usage: $(basename ${BASH_SOURCE[0]}) risk"
+usage() {
+  echo "Usage: $(basename ${BASH_SOURCE[0]}) risk [--providers <providers>]"
+}
+
+if [ "$#" -lt 1 ]; then
+  usage
+  echo "Error: unspecified risk"
   exit 1
 fi
 
-set -e
+RISK=$1
+shift
 
-echo "Installing Checkbox debian packages at risk: $RISK"
+if [ "$1" = "--providers" ]; then
+  shift
+  PROVIDERS="$@"
+  if [ -z "$PROVIDERS" ]; then
+    usage
+    echo "Error: unspecified providers"
+    exit 1
+  fi
+elif [ "$#" -ne 0 ]; then
+  usage
+  echo "Error: unknown arguments $@"
+  exit 1
+fi
+
+log "Installing Checkbox debian packages at risk: $RISK"
 echo "  PPA that will be used: ppa:checkbox-dev/$RISK"
 echo "  See: https://code.launchpad.net/~checkbox-dev/+archive/ubuntu/$RISK"
+[ -n "$PROVIDERS" ] && echo "  Additional providers: $PROVIDERS"
 
-RISK=$1
+set -e
 
 wait_for_packages_complete
 _run sudo add-apt-repository ppa:checkbox-dev/$RISK
-_run install_packages checkbox-ng python3-checkbox-ng checkbox-provider-base checkbox-provider-resource checkbox-provider-sru fswebcam obexftp wmctrl iperf mesa-utils vim pastebinit fwts xorg-dev gir1.2-clutter-1.0
+_run install_packages \
+  checkbox-ng python3-checkbox-ng \
+  checkbox-provider-base checkbox-provider-resource checkbox-provider-sru $PROVIDERS \
+  fswebcam obexftp wmctrl iperf mesa-utils vim pastebinit fwts xorg-dev gir1.2-clutter-1.0
 wait_for_packages_complete
 
 export CHECKBOX_VERSION=$(_run checkbox-cli --version)
 [ -z "$CHECKBOX_VERSION" ] && echo "Error: Unable to retrieve Checkbox version from device" && exit 1
 
-echo "Installing checkbox $CHECKBOX_VERSION on the agent container from source"
+log "Installing checkbox $CHECKBOX_VERSION on the agent container from source"
 install_checkbox_agent_source $CHECKBOX_VERSION
 
 check_for_checkbox_service
