refactor(scriptlets): assume scriptlets are in the PATH

diff --git a/scriptlets/install_packages b/scriptlets/install_packages
--- a/scriptlets/install_packages
+++ b/scriptlets/install_packages
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 usage() {
-    echo $@
+    echo "Usage: $(basename ${BASH_SOURCE[0]}) [--no-update] -- <apt-get install arguments>"
 }
 
 parse_args() {
@@ -28,8 +28,12 @@ parse_args() {
 
 parse_args $@
 
-source "$(dirname "$BASH_SOURCE")/defs/ssh_options"
-$(executable "wait_for_packages_complete")
+wait_for_packages_complete
+result=$?
+if [ $result -gt 0 ]; then
+    echo "Error: unable to complete $(basename ${BASH_SOURCE[0]})"
+    exit $result
+fi
 
 [ -n "$NO_UPDATE" ] || sudo apt-get -qq update
 sudo DEBIAN_FRONTEND=noninteractive apt-get -qqy install -o Dpkg::Options::="--force-confdef" $INSTALL_ARGS
diff --git a/scriptlets/wait_for_packages_complete b/scriptlets/wait_for_packages_complete
--- a/scriptlets/wait_for_packages_complete
+++ b/scriptlets/wait_for_packages_complete
@@ -18,7 +18,7 @@
 # https://man7.org/linux/man-pages/man1/timeout.1.html
 
 usage() {
-    echo "Usage: $(basename $0)"
+    echo "Usage: $(basename ${BASH_SOURCE[0]})"
 }
 
 parse_args() {
@@ -31,15 +31,11 @@ parse_args() {
 
 parse_args $@
 
-source "$(dirname "$BASH_SOURCE")/defs/executable"
-executable "check_for_packages_complete"
+timeout 10m retry --delay 5 -- check_for_packages_complete
 
-echo $BASH_SOURCE
-# timeout 10m retry --delay 5 -- $(executable "check_for_packages_complete")
-
-#result=$?
-#if [ $result -ge 124 ]; then
-#    echo "Unable to complete $(basename $0)$REMOTE_MESSAGE (timeout). Killing apt, apt-get, and dpkg processes."
-#    sudo pkill -x "apt|apt-get|dpkg"
-#fi
-#exit $result
+result=$?
+if [ $result -ge 124 ]; then
+    echo "Unable to complete $(basename ${BASH_SOURCE[0]}) (timeout). Killing apt, apt-get, and dpkg processes."
+    sudo pkill -x "apt|apt-get|dpkg"
+fi
+exit $result
