chore: handle the case where `get_runtime` cannot determine runtime (#69)
* chore: handle the case where `get_runtime` cannot determine runtime
* feat: introduce snapstore package
* chore: modify `install_checkbox_snaps` to use `snapstore-info`
* chore: install `snapstore` in install-tools.sh
* chore: remove get-auth.py and its deb dependency

diff --git a/scriptlets/install_checkbox_snaps b/scriptlets/install_checkbox_snaps
--- a/scriptlets/install_checkbox_snaps
+++ b/scriptlets/install_checkbox_snaps
@@ -60,33 +60,24 @@ get_runtime() {
     local RUNTIME_NAME
 
     # get the snap info from the snap store and extract the base
-    SNAPSTORE_URL="https://api.snapcraft.io/v2/snaps/info/$FRONTEND_NAME?fields=base"
-    SNAPINFO=$(curl -s -H 'Snap-Device-Series: 16' \
-        ${STORE:+ -H "Snap-Device-Store: $STORE"} \
-        ${UBUNTU_STORE_AUTH:+ -H "Authorization: $($TOOLS_PATH/cert-tools/snapcraft/get-auth.py $UBUNTU_STORE_AUTH)"} \
-        "$SNAPSTORE_URL")
-    BASE=$(jq -r \
-      --arg FRONTEND_TRACK $FRONTEND_TRACK \
-      --arg RISK $RISK \
-      --arg ARCH $(get_ubuntu_arch) \
-      '.["channel-map"] | .[] |
-       select(
-         .channel.track == $FRONTEND_TRACK and
-         .channel.risk == $RISK and
-         .channel.architecture == $ARCH
-        ) |
-        .base' <<< $SNAPINFO
+    SNAPINFO=$(snapstore-info \
+        $FRONTEND_NAME $FRONTEND_TRACK/$RISK $(get_ubuntu_arch) \
+        ${STORE:+ --store $STORE} --fields base
     )
+    BASE=$(jq -r '.base' <<< $SNAPINFO)
     # use the base as a heuristic to derive the Checkbox runtime
     if [ "$BASE" = "core" ] || [ "$BASE" = "null" ]; then
       # base: core or undefined -> runtime: checkbox16
-      RUNTIME_NAME=checkbox16
+      RUNTIME_SUFFIX=16
     else
       # base coreYY -> runtime checkboxYY
-      # (the final "grep ." will cause the command to fail if there's no match)
-      RUNTIME_NAME="checkbox$(echo $BASE | sed -n 's/^core\([0-9]\{2\}\)$/\1/p' | grep .)"
+      RUNTIME_SUFFIX=$(echo $BASE | sed -n 's/^core\([0-9]\{2\}\)$/\1/p')
     fi
-    echo $RUNTIME_NAME
+    if [ -z "$RUNTIME_SUFFIX" ]; then
+        echo "Unable to determine runtime for $FRONTEND_NAME=$FRONTEND_TRACK/$RISK"
+        return 1
+    fi
+    echo checkbox$RUNTIME_SUFFIX
 }
 
 install_checkbox_frontend_snap_on_device() {
@@ -173,6 +164,7 @@ export STORE=$(_run "snap model --assertion" | sed -n 's/^store:\s\(.*\)$/\1/p')
 
 # use the frontend to derive the Checkbox runtime to be installed
 export RUNTIME_NAME=$(get_runtime $FRONTEND_NAME $FRONTEND_TRACK $RISK)
+[ "$?" -ne 0 ] && exit 1
 RUNTIME_CHANNEL="latest/$RISK"
 
 # install Checkbox runtime
