[CERTTF-337] feat: Re-implement and extend scriptlets (#36)
* feat(scriptlets): introduce reimplmented and new scriptlets

* feat(scriptlets): Improve waiting for package-handling

* feat (scriptlets): wait for package-handling before installing `psmisc`

* fix: correct command-line argument

* fix: correct remote execution on `install_psmisc`

* refactor: move `scriptlet_path` into `scriptlet/defs`

* refactor: improve how select scriptlets are copied to the device

* fix(scriptlets): make default wait for `retry` 10 seconds

* feat(scriptlets): Remove scriptlet testing

* feat(scriptlets): flexible arguments for `install_packages`, no `--` required

* fix: correct typo

* feat(scriptlets): make `install_psmisc` more verbose

* feat(scriptlets): add scriptlets for monitoring specific snap changes

* Story resources files *temporarily* in tools repo

* feat(scriptlets): check that the Checkbox service is active

* fix(scriptlets): flexible comparison for result returned by `systemctl`

* feat(scriptlets): specify target for `_put` using a colon

* fix(scriptlets): update `_put` in `install_tools.sh` to use colon

* chore(scriptlets): remove resource files for CHECKBOX-1447

* feat: install psmisc only on the device, not the agent

* fix(scriptlets): remove `-t` option for `ssh` (in the `_run` scriptlet)

* fix: check that remote path directory actually exists

* fix: ensure that a remote scriptlet path will exist

* fix: allow `scriptlets_path` to handle Core images with ro filesystems

* fix: allow `install_psmisc` to handle Core images with no package-handling

* feat: install and use `pipx` for packages with CLI entrypoints

* feat: add check/wait for snap changes

* fix: handle pipefails correctly when checking for snap changes

diff --git a/scriptlets/wait_for_ssh b/scriptlets/wait_for_ssh
--- a/scriptlets/wait_for_ssh
+++ b/scriptlets/wait_for_ssh
@@ -1,33 +1,52 @@
 #!/usr/bin/env bash
 
-# Wait until SSH is available on a remote device.
+# Wait until a remote device is fully up and running.
+# 
+# See `check_for_ssh` (which is repeatedly called here) for details
 #
-# This works by repeated attempts to connect to the device via SSH
-# until successful or until a timeout is reached.
-#
-# Dependencies:
-#   This script depends on the `_run` scriptlet
-#
-# Usage:
-#   `wait_for_ssh [attempts]`
+# Return value:
+# 
+# 0 if `check_for_ssh` is successful
+# 1 if `check_for_ssh` cannot be executed or is unsuccesful on the last retry
+# >=124 in case of a timeout waiting for `check_for_ssh` on the last retry
+# https://manpages.ubuntu.com/manpages/focal/man1/retry.1.html
+# https://man7.org/linux/man-pages/man1/timeout.1.html
 
-wait_for_ssh_function() {
-    local attempts=${1:-20} # If no argument is passed, default to 20
-    local loopcnt=0
-    until timeout 10 _run /bin/true
-    do
-        echo "Testing to see if system is back up"
-        loopcnt=$((loopcnt+1))
-        if [ $loopcnt -gt $attempts ]; then
-            echo "ERROR: Timeout waiting for ssh!"
-            return 1
-        fi
-        sleep 30
-    done
-    return 0
+usage() {
+    echo "Usage: $(basename ${BASH_SOURCE[0]}) [--allow-degraded]"
 }
 
-# Check if the script is being sourced or executed
-if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
-    wait_for_ssh_function "$@"
+TIMES=20
+DELAY=10
+while [[ "$#" -gt 0 ]]; do
+    case $1 in
+        --allow-degraded)
+            ALLOW_DEGRADED=$1
+            ;;
+        --times)
+            TIMES=$2
+            shift
+            ;;
+        --delay)
+            DELAY=$2
+            shift
+            ;;
+        *)
+            usage
+            echo "Error: Invalid argument $1"
+            exit 1
+            ;;
+    esac
+    shift
+done
+
+CHECK=check_for_ssh
+# use `retry` to call `check_for_ssh` repeatedly
+retry --times $TIMES --delay $DELAY --message $CHECK -- \
+$CHECK $ALLOW_DEGRADED
+
+result=$?
+if [ $result -gt 0 ]; then
+    echo "Error: unable to complete $(basename ${BASH_SOURCE[0]})"
 fi
+exit $result
