Refine Diagnostic #7

diff --git a/.github/workflows/testflinger_submit.yaml b/.github/workflows/testflinger_submit.yaml
--- a/.github/workflows/testflinger_submit.yaml
+++ b/.github/workflows/testflinger_submit.yaml
@@ -11,12 +11,19 @@ jobs:
     - name: Checkout tools repo
       uses: actions/checkout@v4
     - name: Diagnostic
-      continue-on-error: true
       shell: bash {0}
       run: |
-        status=$(curl -I -w "%{http_code}\n" -o /dev/null -s https://testflinger.canonical.com/agents)
+        status=$(curl -I -w "%{http_code}\n" -o /dev/null -s https://testflinger.canonical.com/jobs)
         error=$?
-        [ $error -eq 0 ] && echo status=$status || echo error=$error
+        if [ ! $error -eq 0 ]; then
+          echo "Unable to ping Testflinger server at https://testflinger.canonical.com"
+          exit $error
+        elif [ ! $status -eq 200 ]; then
+          echo "Failed server ping at https://testflinger.canonical.com, error status: $status"
+          exit $status
+        else
+          echo "Successful server ping at https://testflinger.canonical.com, status: $status"
+        fi
     - name: Submit job
       uses: canonical/testflinger/.github/actions/submit@main
       with:
